name: deptest

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build for ddd
        run: |
            echo "built"
            
  deployment:
    runs-on: ubuntu-latest
    environment: ddd
    steps:
    
      - name: deploy to ddd
        run: |
            echo "deployed"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: test for ddd
        run: |
            echo "tested"
