name: deptest

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker build
        run: |
            echo "built"
            
  deployment-test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Deploy to test env
        run: |
            echo "deployed to test"

  rollback-test:
    runs-on: ubuntu-latest
    needs: deployment-test
    environment: test
    steps:
      - name: Rollback test env
        run: |
            echo "rolled back from prod"

  deployment-prod:
    runs-on: ubuntu-latest
    needs: deployment-test
    environment: prod
    steps:
      - name: Deploy to prod env
        run: |
            echo "deployed to prod"

  rollback-prod:
    runs-on: ubuntu-latest
    needs: deployment-prod
    environment: prod
    steps:
      - name: Rollback prod env
        run: |
            echo "rolled back from prod"
